(function(){'use strict';const UK='sanad_users_v1',SK='sanad_auth_session_v1';
function users(){try{return JSON.parse(localStorage.getItem(UK)||'[]')}catch(_){return []}} function save(u){localStorage.setItem(UK,JSON.stringify(u))} function id(){return'u_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)} function email(v){return String(v||'').trim().toLowerCase()}
function seed(){let u=users();if(!u.some(x=>x.role==='admin'))u.push({id:id(),name:'مدير سند',email:'admin@sanad.local',password:'Sanad@2027a',role:'admin',createdAt:Date.now()});if(!u.some(x=>x.email==='student@sanad.local'))u.push({id:id(),name:'طالب تجريبي',email:'student@sanad.local',password:'Student123!',role:'user',createdAt:Date.now()});save(u)}
function session(){try{return JSON.parse(sessionStorage.getItem(SK)||localStorage.getItem(SK)||'null')}catch(_){return null}}
function login(e,p,remember){const u=users().find(x=>x.email===email(e)&&x.password===String(p||''));if(!u)return{success:false,error:'البريد الإلكتروني أو كلمة المرور غير صحيحة.'};const s={userId:u.id,name:u.name,email:u.email,role:u.role};sessionStorage.removeItem(SK);localStorage.removeItem(SK);(remember?localStorage:sessionStorage).setItem(SK,JSON.stringify(s));return{success:true,session:s}}
function register(d){let u=users(),e=email(d.email);if(!d.name?.trim())return{success:false,error:'الاسم مطلوب.'};if(!/^\S+@\S+\.\S+$/.test(e))return{success:false,error:'أدخل بريدًا إلكترونيًا صحيحًا.'};const pw=String(d.password||'');if(pw.length<8||!/[a-z]/.test(pw)||!/[A-Z]/.test(pw)||!/[0-9]/.test(pw)||!/[^A-Za-z0-9\s]/.test(pw))return{success:false,error:'كلمة المرور يجب أن تكون قوية: 8 أحرف على الأقل، مع حرف كبير وصغير ورقم ورمز خاص.'};if(u.some(x=>x.email===e))return{success:false,error:'هذا البريد مسجل مسبقًا.'};u.push({id:id(),name:d.name.trim(),email:e,password:String(d.password),role:'user',createdAt:Date.now()});save(u);return login(e,d.password,true)}
function resetPassword(e,p){let u=users(),i=u.findIndex(x=>x.email===email(e));if(i<0)return{success:false,error:'لا يوجد حساب بهذا البريد.'};const pw=String(p||'');if(pw.length<8||!/[a-z]/.test(pw)||!/[A-Z]/.test(pw)||!/[0-9]/.test(pw)||!/[^A-Za-z0-9\s]/.test(pw))return{success:false,error:'كلمة المرور الجديدة يجب أن تكون قوية: 8 أحرف على الأقل، مع حرف كبير وصغير ورقم ورمز خاص.'};u[i].password=String(p);save(u);return{success:true}}
function logout(){sessionStorage.removeItem(SK);localStorage.removeItem(SK);location.href='./login.html'}
function requireAuth(role){const s=session();if(!s){location.replace('./login.html');return null}if(role&&s.role!==role){location.replace('./index.html');return null}return s}
function updateUser(i,p){let u=users(),n=u.findIndex(x=>x.id===i);if(n<0)return{success:false};u[n]={...u[n],...p,id:u[n].id};save(u);return{success:true}}
function deleteUser(i){let s=session(),u=users(),t=u.find(x=>x.id===i);if(s?.userId===i)return{success:false,error:'لا يمكنك حذف حسابك الحالي.'};if(t?.role==='admin'&&u.filter(x=>x.role==='admin').length<=1)return{success:false,error:'يجب أن يبقى حساب أدمن واحد على الأقل.'};save(u.filter(x=>x.id!==i));return{success:true}}
seed();window.SanadAuth={users,session,login,register,resetPassword,logout,requireAuth,updateUser,deleteUser};const page=location.pathname.split('/').pop()||'index.html';if(page==='index.html'||page===''){const s=requireAuth();if(s)window.addEventListener('DOMContentLoaded',()=>{const c=document.getElementById('auth-user-chip');if(c)c.textContent='👤 '+s.name;const a=document.getElementById('admin-panel-link');if(a&&s.role==='admin')a.style.display='inline-flex';document.getElementById('btn-logout')?.addEventListener('click',logout)})}})();
